spring.application.name=basket
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.jpa.hibernate.ddl-auto=create-drop
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

rabbitmq.exchange=donation.exchange
rabbitmq.queue=donation.requests.queue
rabbitmq.routingKey=donation.routingKey

camel.component.activemq.broker-url=tcp://localhost:61616
camel.component.activemq.username=admin
camel.component.activemq.password=admin

activemq.queueName=activemq:queue:donation.requests.queue

management.endpoints.web.exposure.include=prometheus,health,info
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true
management.metrics.tags.application=BasketInterceptorApplication

proxy.security.token=SecureBasketToken2026


camunda.bpm.deployment-resource-pattern=classpath*:/processes/**/*.bpmn
camunda.bpm.admin-user.id=demo
camunda.bpm.admin-user.password=demo
camunda.bpm.admin-user.first-name=Demo
camunda.bpm.admin-user.last-name=Demo
camunda.bpm.history-level=full
camunda.bpm.id=default

spring.kafka.bootstrap-servers=localhost:9092
